# Generated by Django 4.2.9 on 2024-08-21 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=30, null=True)),
                ('sports_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_created=True)),
                ('team_name', models.CharField(max_length=20, null=True)),
                ('coach', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.sports')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('jersey_number', models.IntegerField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('skill_level', models.CharField(max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
